Expose public #open method
dry-rb/dry-files pull request #9
Opened 2022-07-15 02:55 UTC by alassek

There is currently no way to get a persistent file handle from the public interface. 

You sometimes want to do this, e.g. for defining a log device. It would be nice to test log output without writing to the actual FS. I've worked around this by making `StringIO` injectable through configuration, but that's an annoying special case and using a virtual FS during test would be really convenient.

When a block is not passed to File.open, it returns the open file instance. `MemoryFileSystem` was not doing this, making the interfaces inconsistent.

I'm unsure if this should be specifically documented; basically this makes `#open` work like `File.open` so it should not be surprising, but also it is somewhat problematic since you have to clean up the file handle manually.

2022-07-26 04:50 UTC, solnic approved these changes
Looks like a useful addition, thank you 👍🏻 @jodosha are you ok with adding this?

2022-08-02 08:46 UTC, jodosha requested changes
@alassek Thanks for this PR.

Could you please address my comments? Thanks 🙏

2022-08-02 08:46 UTC, jodosha commented on lib/dry/files.rb
> +    # @since 0.2.0
```suggestion
    # @since 0.3.0
```

2022-08-02 08:46 UTC, jodosha commented on lib/dry/files.rb
> +    # @api private
@alassek If this is passed as default argument to `#open`, which is a public method, by consequence, this is public API as well.
```suggestion
    # @api public
```

2022-08-02 08:46 UTC, jodosha commented on lib/dry/files.rb
> +    private_constant :OPEN_MODE
@alassek This is no longer a private constant.

```suggestion
```

2022-08-02 08:46 UTC, jodosha commented on lib/dry/files/file_system.rb
>        WRITE_MODE = (::File::CREAT | ::File::WRONLY | ::File::TRUNC).freeze
@alassek move this constant as well. Make it Public API.

2022-08-02 08:46 UTC, jodosha commented on spec/unit/dry/files/file_system_spec.rb
> +        subject.open(path, ::File::RDWR) do |file|
```suggestion
        subject.open(path, Dry::Files::OPEN_MODE) do |file|
```

2022-08-02 08:46 UTC, jodosha commented on spec/unit/dry/files/file_system_spec.rb
> +        subject.open(path, ::File::RDWR) do |file|
```suggestion
        subject.open(path, Dry::Files::OPEN_MODE) do |file|
```

2022-08-02 08:46 UTC, jodosha commented on spec/unit/dry/files/file_system_spec.rb
> +        file = subject.open(path, ::File::RDWR)
```suggestion
        file = subject.open(path, Dry::Files::OPEN_MODE)
```

2022-08-02 08:46 UTC, jodosha commented on spec/unit/dry/files/memory_file_system_spec.rb
> +        subject.open(path, File::RDWR) do |file|
```suggestion
        subject.open(path, Dry::Files::OPEN_MODE) do |file|
```

2022-08-02 08:46 UTC, jodosha commented on spec/unit/dry/files/memory_file_system_spec.rb
> +        subject.open(path, File::RDWR) do |file|
```suggestion
        subject.open(path, Dry::Files::OPEN_MODE) do |file|
```

2022-08-02 08:46 UTC, jodosha commented on spec/unit/dry/files/memory_file_system_spec.rb
> +        file = subject.open(path, File::RDWR)
```suggestion
        file = subject.open(path, Dry::Files::OPEN_MODE)
```

2022-08-02 22:27 UTC, alassek commented
@jodosha Thanks for the review! All requested changes have been implemented.

2022-08-05 06:27 UTC, jodosha approved these changes
@alassek Wonderful!

I wish OSS was always made of smooth collaborations like this. You were super reactive, and on point.

Thank you, Adam. 🙏

2022-08-05 06:28 UTC, merged